# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa9360e21c4696c1fbb4b869c136fc924aceec5c23b597673d6c447b7223f0e81b56233456177c9cb424e47016c456a9ef273fe66b509789b92251344e29df8c

test:
  secret_key_base: 25af58a4b9f6f3ce011a439c11c473d6b0962706baacaf364471a2c6359055a91da865331308cfd62db54622e30f79a4c2218935c3a3364fd4d6e97a4c845587

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
